import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { atomicWrite, readJson, contentHash, normalizeTitle } from "../src/lib/source-first.js";
import { numericEvidenceIssues } from "../src/lib/evidence.js";
const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const ISSUES = path.join(ROOT, "data", "issues");
const TERMS = path.join(ROOT, "data", "editorial", "terminology.json");
function issues() { return fs.readdirSync(ISSUES).filter((f) => /^\d{4}-\d{2}-\d{2}\.json$/.test(f)).flatMap((file) => { const d = readJson(path.join(ISSUES, file), {}); return (d.items || []).map((x) => ({ ...x, _date: d.date || file.slice(0, 10) })); }); }
function textOf(a) { return [a.titleKo, a.leadKo, ...(a.bodyKo || []), ...(a.keyPointsKo || []), a.angleKo, a.radar?.clinical, a.radar?.owner?.q, a.radar?.owner?.script, a.radar?.evidence].filter(Boolean).join(" "); }
function numbers(value) { return [...String(value || "").matchAll(/\b\d+(?:[,.]\d+)?\s*(?:mg|μg|mcg|mL|ml|IU|%|개월|주|일|마리|명|세)?\b/gi)].map((m) => m[0].replace(/\s+/g, " ").trim()); }
function write(name, data, md) { atomicWrite(path.join(ROOT, "reports", `${name}.json`), JSON.stringify(data, null, 2) + "\n"); atomicWrite(path.join(ROOT, "reports", `${name}.md`), md); }
export function loadTerminology() { return readJson(TERMS, { version: 1, terms: [] }); }
export function auditTerminology(rows = issues()) { const terms = loadTerminology().terms || []; const matches = []; const warnings = []; for (const a of rows) { const text = textOf(a); for (const term of terms) { const found = [term.canonicalKo, ...(term.aliases || [])].filter(Boolean).filter((x) => text.includes(x)); if (found.length) matches.push({ id: a.id, title: a.titleKo, canonicalKo: term.canonicalKo, matched: found, reviewRequired: Boolean(term.reviewRequired) }); for (const forbidden of term.forbiddenTranslations || []) if (forbidden && text.includes(forbidden)) warnings.push({ id: a.id, title: a.titleKo, term: term.canonicalKo, forbidden }); } } return { generatedAt: new Date().toISOString(), termCount: terms.length, articleCount: rows.length, matchCount: matches.length, warningCount: warnings.length, matches, warnings }; }
export function auditLanguage(rows = issues()) { const known = ["병원ugeom", "강아지 주인의 위한", "무뎌지", "원-health", "조객 참여", "백식", "백석", "각제", "수아지"]; const result = []; for (const a of rows) { const text = textOf(a); const warnings = []; if (/[가-힣][A-Za-z]{2,}[가-힣]/.test(text)) warnings.push("korean-internal-ascii"); for (const p of known) if (text.includes(p)) warnings.push(`known-error:${p}`); if (/\b(?:the|and|with|for|from|study|patient|randomized)\b/i.test(String(a.titleKo || ""))) warnings.push("untranslated-title"); if (/\b(최초|입증|완치)\b/.test(text)) warnings.push("claim-superlative-review"); const paragraphs = (a.bodyKo || []).filter((p) => String(p).trim()); if (paragraphs.length > 1 && new Set(paragraphs.map((p) => normalizeTitle(p))).size < paragraphs.length) warnings.push("repeated-paragraph"); if (warnings.length) result.push({ id: a.id, date: a._date, title: a.titleKo, warnings: [...new Set(warnings)], contentHash: a.contentHash || contentHash(text) }); } return { generatedAt: new Date().toISOString(), articleCount: rows.length, warningCount: result.length, blockerCount: result.filter((x) => x.warnings.some((w) => /known-error|korean-internal-ascii/.test(w))).length, rows: result }; }
export function auditClaims(rows = issues()) { const result = []; for (const a of rows) { const text = textOf(a); const title = String(a.sourceTitle || ""); const n = numbers(text); const warnings = [...new Set([...(numericEvidenceIssues(a) || []), ...(a.evidence?.studyType && /증례|case report/i.test(String(a.evidence.studyType)) && /모든|일반적으로|입증|효과가 있다/.test(text) ? ["case-report-generalization"] : []), (/\b(최초|입증|완치)\b/.test(text) && !/\b(최초|입증|완치)\b/.test(title) ? ["unsupported-claim"] : []), (a.evidence?.speciesStudied && a.species?.length && !String(a.evidence.speciesStudied).split(/[,/·]/).some((s) => a.species.includes(s.trim())) ? ["species-mismatch"] : [])].flat())]; const claim = { claim: a.radar?.clinical || a.leadKo || a.titleKo || "", sourceEvidence: a.sourceUrl ? { url: a.sourceUrl, title: a.sourceTitle || null } : null, evidenceType: a.doi || a.journal ? "paper-metadata" : a.sourceUrl ? "source-page" : "not-available", species: a.evidence?.speciesStudied || a.species || [], population: a.evidence?.sampleSize || null, number: n, unit: n.map((x) => x.replace(/[\d,.\s]/g, "")), confidence: warnings.length ? "review" : a.sourceUrl ? "medium" : "low", reviewRequired: warnings.length > 0 || !a.sourceUrl }; if (warnings.length || claim.reviewRequired) result.push({ id: a.id, date: a._date, title: a.titleKo, warnings, claim }); } return { generatedAt: new Date().toISOString(), articleCount: rows.length, warningCount: result.length, blockerCount: result.filter((x) => x.warnings.some((w) => /species-mismatch|case-report|numeric/.test(w))).length, rows: result }; }
function main() { const command = process.argv[2] || "language"; const data = command === "terminology" ? auditTerminology() : command === "claims" ? auditClaims() : auditLanguage(); const name = `${command}-audit`; const md = `# ${command} audit\n\n- 실행 시각: ${data.generatedAt}\n- 대상 기사: ${data.articleCount}\n- 경고: ${data.warningCount}\n- 차단 후보: ${data.blockerCount}\n\n${(data.rows || data.warnings || []).slice(0, 500).map((x) => `- ${x.id} · ${(x.title || "").slice(0, 100)} · ${(x.warnings || [x.forbidden]).join(", ")}`).join("\n") || "없음"}\n`; write(name, data, md); console.log(JSON.stringify({ articleCount: data.articleCount, warningCount: data.warningCount, blockerCount: data.blockerCount }, null, 2)); }
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
