import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { atomicWrite, readJson } from "../src/lib/source-first.js";
const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
function load(name, fallback) { return readJson(path.join(ROOT, "reports", name), fallback); }
function build() { const ingest = load("ingest-report.json", { drafts: [], counts: {} }); const updates = load("update-candidates.json", { rows: [], counts: {} }); const feed = load("feed-diagnostics.json", { feeds: [], counts: {} }); const claims = load("claims-audit.json", { rows: [] }); const language = load("language-audit.json", { rows: [] }); const draftRows = (ingest.drafts || []).map((d) => ({ ...d, status: "draft", published: false, title: d.title || d.sourceTitle, canonicalStatus: d.sourceStatus, warnings: [...(claims.rows || []).filter((x) => x.id === d.id).flatMap((x) => x.warnings || []), ...(language.rows || []).filter((x) => x.id === d.id).flatMap((x) => x.warnings || [])], imageStatus: d.imageOwnership || "검수 필요", priority: d.clinicalRisk === "high" ? 100 : d.clinicalRisk === "medium" ? 70 : 40, commands: { show: `npm run review:show -- ${d.id}`, promote: `npm run ingest:promote -- ${d.id}` } })); const queue = ["high", "medium", "low"].flatMap((risk) => draftRows.filter((x) => x.clinicalRisk === risk).map((x) => ({ type: "draft", id: x.id, title: x.title, risk, score: x.priority, reason: `${risk}-risk 신규 draft · 사람 승인 필요` }))); const old = load("review-export.json", { rows: [] }).rows || []; queue.push(...old.filter((x) => x.indexable && ["high", "medium"].includes(x.clinicalRisk)).slice(0, 200).map((x) => ({ type: "legacy-review", id: x.id, title: x.title, risk: x.clinicalRisk, score: x.clinicalRisk === "high" ? 100 : 80, reason: `legacy ${x.clinicalRisk}-risk index 기사 검수 대기` }))); queue.push(...(updates.rows || []).filter((x) => x.classification === "substantive-update" || x.classification === "correction").map((x) => ({ type: "update", id: x.candidateId, title: x.candidate.title, risk: "review", score: x.classification === "correction" ? 110 : 75, reason: x.classification }))); queue.sort((a, b) => b.score - a.score || a.id.localeCompare(b.id)); return { generatedAt: new Date().toISOString(), noindex: true, summary: { drafts: draftRows.length, queue: queue.length, feedCount: (feed.feeds || []).length, updates: (updates.rows || []).length, unpublished: draftRows.filter((x) => !x.published).length }, drafts: draftRows, feedDiagnostics: feed, updates, queue, note: "인증 관리자 전용 읽기 데이터. draft는 공개 빌드·sitemap·RSS에 포함되지 않습니다." }; }
function save(data) { atomicWrite(path.join(ROOT, "reports", "draft-newsroom.json"), JSON.stringify(data, null, 2) + "\n"); atomicWrite(path.join(ROOT, "reports", "draft-newsroom.md"), `# Draft 뉴스룸\n\n- draft: ${data.summary.drafts}\n- 통합 큐: ${data.summary.queue}\n- update 후보: ${data.summary.updates}\n\n${data.queue.slice(0, 100).map((x) => `- ${x.score} · ${x.type} · ${x.id} · ${x.title} · ${x.reason}`).join("\n")}\n`); return data; }
const data = save(build()); console.log(JSON.stringify(data.summary, null, 2));
