import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { atomicWrite, readJson } from "../src/lib/source-first.js";
import { organizationAuthor } from "../src/lib/editorial-policy.js";
const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

export function buildPackage(row) {
  return { generatedAt: new Date().toISOString(), previewOnly: true, eligibleForPublish: false, reason: "실제 reviewerId와 사람 승인 기록이 없습니다", title: row.title, description: row.description || null, canonical: row.sourceUrl || null, contentTier: row.contentTier || "brief", clinicalRisk: row.clinicalRisk || null, editorialStatus: row.editorialStatus || "editor-review-required", source: { label: row.sourceLabel, title: row.title, url: row.sourceUrl, rawUrl: row.sourceUrlRaw, publishedAt: row.publishedAt }, evidence: row.evidence || null, image: { url: row.imageUrl || null, ownership: row.imageOwnership || "unknown", alt: row.imageAlt || null }, author: organizationAuthor(), reviewer: null, relatedArticles: [], jsonLd: { "@context": "https://schema.org", "@type": "NewsArticle", headline: row.title, description: row.description || "", ...(row.sourceUrl ? { isBasedOn: { "@type": "CreativeWork", url: row.sourceUrl } } : {}), author: organizationAuthor() }, rss: { title: row.title, description: row.description || "", guid: row.id, link: row.sourceUrl || null }, sitemap: { included: false, reason: "preview-only draft" }, quality: { warnings: row.warnings || [], passed: !(row.warnings || []).length } };
}
export function writePackage(row) { const pkg = buildPackage(row); const dir = path.join(ROOT, "reports", "prepublish"); fs.mkdirSync(dir, { recursive: true }); atomicWrite(path.join(dir, `${row.id}.json`), JSON.stringify(pkg, null, 2) + "\n"); atomicWrite(path.join(dir, `${row.id}.md`), `# 발행 전 패키지\n\n- 제목: ${row.title}\n- source: ${row.sourceUrl || "미확정"}\n- 상태: preview-only\n- 발행 가능: 아니오\n- 경고: ${(row.warnings || []).join(", ") || "없음"}\n`); return pkg; }
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) { const id = process.argv[2]; const newsroom = readJson(path.join(ROOT, "reports", "draft-newsroom.json"), { drafts: [] }); const row = newsroom.drafts.find((x) => x.id === id) || newsroom.drafts[0]; if (!row) { console.error("draft 후보가 없습니다"); process.exit(1); } console.log(JSON.stringify({ id: row.id, previewOnly: true, eligibleForPublish: false, ...writePackage(row) }, null, 2)); }
