import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";
import { articleContractIssues, checklistComplete, contentHash, requiredReviewRole, sourceHash } from "../src/lib/editorial-operations.js";
import { inferClinicalRisk } from "../src/lib/editorial-review.js";
import { publishQualityIssues } from "../src/quality.js";
import { imageCanRender } from "../src/lib/image-rights.js";
import { isOfficialUrl, isRelayUrl, loadRegistry, readJson, atomicWrite, safeSourceUrl } from "../src/lib/source-first.js";
import { writePackage } from "./prepublish-package.js";
import { isVeterinaryReviewerAvailable, organizationAuthor } from "../src/lib/editorial-policy.js";

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const ISSUES = path.join(ROOT, "data", "issues");
const DRAFTS = path.join(ROOT, "data", "drafts");
const PEOPLE = path.join(ROOT, "data", "editorial", "people.json");
const APPROVALS = path.join(ROOT, "data", "editorial", "publish-approvals.jsonl");
const HISTORY = path.join(ROOT, "data", "editorial", "publish-history.jsonl");
const BACKUPS = path.join(ROOT, ".editorial-backups");
function args() { const raw = process.argv.slice(2); const command = raw.shift() || "validate"; const positional = []; const flags = {}; for (let i = 0; i < raw.length; i += 1) { const token = raw[i]; if (!token.startsWith("--")) { positional.push(token); continue; } const [key, ...rest] = token.slice(2).split("="); flags[key] = rest.length ? rest.join("=") : (raw[i + 1] && !raw[i + 1].startsWith("--") ? raw[++i] : true); } return { command, positional, flags }; }
function people() { const p = readJson(PEOPLE, { people: [] }); return Array.isArray(p) ? p : p.people || []; }
function findDraft(id) { const files = fs.existsSync(DRAFTS) ? fs.readdirSync(DRAFTS).filter((x) => x.endsWith(".json")) : []; for (const file of files) { const data = readJson(path.join(DRAFTS, file), {}); const index = (data.items || []).findIndex((x) => x.id === id); if (index >= 0) return { file, path: path.join(DRAFTS, file), data, index, item: data.items[index] }; } const report = readJson(path.join(ROOT, "reports", "draft-newsroom.json"), { drafts: [] }); const item = (report.drafts || []).find((x) => x.id === id); return item ? { file: null, path: null, data: null, index: -1, item } : null; }
function reviewer(id) { return people().find((p) => p.id === id || p.slug === id) || null; }
function currentHash(item) { return contentHash(item); }
function registrySource(item) { const registry = loadRegistry(); return registry.sources.find((s) => s.id === item.sourceId || s.label === item.sourceLabel) || null; }
function validate(item, person = null) {
  const risk = item.clinicalRisk || inferClinicalRisk(item); const role = requiredReviewRole({ ...item, clinicalRisk: risk }); const source = registrySource(item); const blockers = []; const warnings = [];
  if (!item.sourceUrl || !safeSourceUrl(item.sourceUrl) || isRelayUrl(item.sourceUrl)) blockers.push("공식 직접 sourceUrl 필요");
  if (!source || !isOfficialUrl(item.sourceUrl, source)) blockers.push("레지스트리 공식 도메인 확인 필요");
  if (item.sourceStatus && item.sourceStatus !== "verified") blockers.push(`sourceStatus=${item.sourceStatus}`);
  if (item.duplicateStatus !== "unique") blockers.push(`duplicateStatus=${item.duplicateStatus || "미분류"}`);
  if (!item.titleKo || !item.leadKo || !Array.isArray(item.bodyKo) || !item.bodyKo.length) blockers.push("한국어 title/lead/body 초안 필요");
  blockers.push(...publishQualityIssues(item));
  const contract = articleContractIssues({ ...item, workflowStatus: item.workflowStatus || "draft", publishedAt: item.publishedAt || "scheduled" }).filter((x) => !["publishedAt-missing"].includes(x)); blockers.push(...contract);
  const ownership = item.imageOwnership || (item.imageOrigin === "editorial-card" ? "owned" : null); const imageUrl = item.imageUrl || item.image || null;
  if (!imageUrl || !imageCanRender({ url: imageUrl, ownership, origin: item.imageOrigin })) blockers.push("권리 확인된 대표 이미지 필요");
  if (!person) blockers.push(`등록된 ${role} reviewer 필요`); else if (!new Set(["admin", role]).has(person.role)) blockers.push(`${role} 역할 reviewer 필요`);
  if (!item.reviewChecklist || !checklistComplete(item.reviewChecklist)) blockers.push("완료된 검수 체크리스트 필요");
  if (risk === "high" && (!person || !["vet", "admin"].includes(person.role))) blockers.push("high-risk는 vet 역할 필요");
  if (risk === "high" && !isVeterinaryReviewerAvailable()) blockers.push("현재 등록된 수의사 감수자가 없어 high-risk 승인을 차단했습니다");
  if (person?.role === "vet" && !isVeterinaryReviewerAvailable()) blockers.push("editorialMode=organization-only: veterinaryReviewerAvailable=false");
  if (item.workflowStatus && !["draft", "editor-review-required", "vet-review-required"].includes(item.workflowStatus)) warnings.push(`현재 workflowStatus=${item.workflowStatus}`);
  const jsonLd = { "@context": "https://schema.org", "@type": "NewsArticle", headline: item.titleKo || item.sourceTitle || "", description: item.leadKo || "", author: organizationAuthor(), ...(item.sourceUrl ? { isBasedOn: { "@type": "CreativeWork", url: item.sourceUrl } } : {}) }; try { JSON.parse(JSON.stringify(jsonLd)); } catch { blockers.push("JSON-LD 파싱 실패"); }
  return { id: item.id, risk, requiredRole: role, source: source?.id || null, currentContentHash: currentHash(item), currentSourceHash: sourceHash(item), blockers: [...new Set(blockers)], warnings, expected: { sitemap: false, rss: false, index: false }, jsonLd };
}
function print(plan) { console.log(JSON.stringify(plan, null, 2)); }
function prepare(id) { const row = findDraft(id); if (!row) throw new Error(`draft를 찾을 수 없습니다: ${id}`); const pkg = writePackage(row.item); print({ id, previewOnly: true, eligibleForPublish: false, package: pkg }); }
function validateCommand(id) { const row = findDraft(id); if (!row) throw new Error(`draft를 찾을 수 없습니다: ${id}`); print(validate(row.item)); }
function approve(id, positional, flags) { const row = findDraft(id); if (!row) throw new Error(`draft를 찾을 수 없습니다: ${id}`); const reviewerId = flags.reviewer || flags["reviewer-id"] || positional[1]; const person = reviewer(reviewerId); const plan = validate(row.item, person); const checklist = flags.checklist === "all" || flags.checklist === true; if (!checklist) plan.blockers.push("--checklist=all 필요"); plan.action = "approve"; plan.reviewerId = reviewerId || null; plan.apply = Boolean(flags.apply); print(plan); if (plan.blockers.length) throw new Error(`승인 차단:\n- ${[...new Set(plan.blockers)].join("\n- ")}`); if (!flags.apply) { console.log("dry-run: --apply 없이는 승인 기록을 저장하지 않습니다."); return; } if (!row.path) throw new Error("reports-only draft는 data/drafts 파일로 저장된 뒤 승인할 수 있습니다"); const updated = { ...row.item, workflowStatus: "approved", editorialStatus: person.role === "vet" ? "vet-reviewed" : "editor-reviewed", reviewerId: person.id, reviewerRole: person.role, reviewedBy: person.name, reviewedAt: new Date().toISOString(), contentHash: currentHash(row.item), sourceHash: sourceHash(row.item), reviewChecklist: Object.fromEntries(["sourceConfirmed", "titleLeadBodyChecked", "numbersChecked", "speciesAndStudyChecked", "limitationsChecked", "clinicalLanguageChecked"].map((key) => [key, true])) }; const data = row.data; data.items[row.index] = updated; atomicWrite(row.path, JSON.stringify(data, null, 2) + "\n"); fs.mkdirSync(path.dirname(APPROVALS), { recursive: true }); fs.appendFileSync(APPROVALS, JSON.stringify({ eventId: crypto.randomUUID(), id, reviewerId: person.id, reviewerRole: person.role, approvedAt: updated.reviewedAt, contentHash: updated.contentHash, sourceHash: updated.sourceHash }) + "\n"); }
function approvals() { return fs.existsSync(APPROVALS) ? fs.readFileSync(APPROVALS, "utf8").split(/\r?\n/).filter(Boolean).map((x) => JSON.parse(x)) : []; }
function release(id, flags) { const row = findDraft(id); if (!row) throw new Error(`draft를 찾을 수 없습니다: ${id}`); const approval = approvals().filter((x) => x.id === id).at(-1); if (!approval) throw new Error("사람 승인 기록이 없습니다"); const hash = currentHash(row.item); if (approval.contentHash !== hash) throw new Error("승인 후 contentHash가 변경되어 release를 차단했습니다"); const plan = validate({ ...row.item, workflowStatus: "approved", reviewChecklist: { sourceConfirmed: true, titleLeadBodyChecked: true, numbersChecked: true, speciesAndStudyChecked: true, limitationsChecked: true, clinicalLanguageChecked: true } }, reviewer(approval.reviewerId)); plan.action = "release"; plan.apply = Boolean(flags.apply); print(plan); if (plan.blockers.length) throw new Error(`release 차단:\n- ${plan.blockers.join("\n- ")}`); if (!flags.apply) { console.log("dry-run: --apply 없이는 published issue를 만들지 않습니다."); return; } const date = flags.date || new Date().toISOString().slice(0, 10); const target = path.join(ISSUES, `${date}.json`); const old = readJson(target, { date, status: "published", generatedAt: new Date().toISOString(), items: [] }); const backupDir = path.join(BACKUPS, new Date().toISOString().replace(/[:.]/g, "-")); fs.mkdirSync(backupDir, { recursive: true }); const backup = path.join(backupDir, `${date}.json`); atomicWrite(backup, JSON.stringify(old, null, 2) + "\n"); const published = { ...row.item, workflowStatus: "published", editorialStatus: "published", publishedAt: row.item.publishedAt || new Date().toISOString(), firstPublishedAt: row.item.firstPublishedAt || new Date().toISOString(), updatedAt: row.item.updatedAt || null }; if (!old.items.some((x) => x.id === id)) old.items.push(published); atomicWrite(target, JSON.stringify(old, null, 2) + "\n"); fs.mkdirSync(path.dirname(HISTORY), { recursive: true }); fs.appendFileSync(HISTORY, JSON.stringify({ eventId: crypto.randomUUID(), action: "release", id, file: `data/issues/${date}.json`, backup: path.relative(ROOT, backup), releasedAt: new Date().toISOString(), contentHash: hash }) + "\n"); }
function rollback(id, flags) { const entries = fs.existsSync(HISTORY) ? fs.readFileSync(HISTORY, "utf8").split(/\r?\n/).filter(Boolean).map((x) => JSON.parse(x)).filter((x) => x.id === id && x.backup) : []; const last = entries.at(-1); if (!last) throw new Error("복구할 publish history가 없습니다"); const backup = path.join(ROOT, last.backup); if (!fs.existsSync(backup)) throw new Error("백업 파일이 없습니다"); const target = path.join(ROOT, last.file); const current = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : ""; const plan = { id, target: last.file, backup: last.backup, apply: Boolean(flags.apply), currentHash: crypto.createHash("sha256").update(current).digest("hex") }; print(plan); if (!flags.apply) { console.log("dry-run: --apply 없이는 이전 버전을 복구하지 않습니다."); return; } const rollbackDir = path.join(BACKUPS, `rollback-${new Date().toISOString().replace(/[:.]/g, "-")}`); fs.mkdirSync(rollbackDir, { recursive: true }); atomicWrite(path.join(rollbackDir, path.basename(target)), current); atomicWrite(target, fs.readFileSync(backup, "utf8")); fs.appendFileSync(HISTORY, JSON.stringify({ eventId: crypto.randomUUID(), action: "rollback", id, restoredFrom: last.backup, rollbackBackup: path.relative(ROOT, path.join(rollbackDir, path.basename(target))), at: new Date().toISOString() }) + "\n"); }
const { command, positional, flags } = args(); try { if (command === "prepare") prepare(positional[0]); else if (command === "validate") validateCommand(positional[0]); else if (command === "approve") approve(positional[0], positional, flags); else if (command === "release") release(positional[0], flags); else if (command === "rollback") rollback(positional[0], flags); else throw new Error("prepare ID | validate ID | approve ID --reviewer ID [--checklist=all] | release ID | rollback ID"); } catch (error) { console.error(error.message); process.exit(1); }
