import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { atomicWrite, contentHash, normalizeTitle, readJson, titleSimilarity } from "../src/lib/source-first.js";
const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const ISSUES = path.join(ROOT, "data", "issues");
const REPORT = path.join(ROOT, "reports", "ingest-report.json");
const OUT = path.join(ROOT, "reports", "update-candidates.json");
const DECISIONS = path.join(ROOT, "data", "editorial", "update-decisions.jsonl");
function existing() { return fs.readdirSync(ISSUES).filter((f) => /^\d{4}-\d{2}-\d{2}\.json$/.test(f)).flatMap((file) => { const d = readJson(path.join(ISSUES, file), {}); return (d.items || []).map((x) => ({ ...x, _date: d.date || file.slice(0, 10) })); }); }
function drafts() { const r = readJson(REPORT, { drafts: [], updateCandidates: [] }); return r.updateCandidates || []; }
function bodyOf(a) { return [a.titleKo, a.leadKo, ...(a.bodyKo || []), ...(a.keyPointsKo || []), a.description, a.sourceTitle].filter(Boolean).join(" "); }
function numbers(a) { return [...bodyOf(a).matchAll(/\b\d+(?:[,.]\d+)?\s*(?:mg|μg|mcg|mL|ml|IU|%|개월|주|일|마리|명|세)?\b/gi)].map((m) => m[0].replace(/\s+/g, " ")); }
export function classifyUpdate(candidate, prior) { if (!prior) return candidate.sourceStatus === "verified" ? "separate-story" : "unresolved"; const titleScore = titleSimilarity(candidate.title || candidate.sourceTitle, prior.sourceTitle || prior.titleKo || prior.title); const sameSource = [candidate.sourceUrl, candidate.sourceUrlRaw, candidate.canonicalUrl].filter(Boolean).some((u) => [prior.sourceUrl, prior.sourceUrlRaw, prior.canonicalUrl].filter(Boolean).includes(u)); const candidateNums = numbers(candidate); const priorNums = numbers(prior); if (sameSource && candidateNums.join("|") === priorNums.join("|")) return titleScore >= .9 ? "duplicate" : "minor-update"; if (sameSource && /(?:correction|erratum|retraction|withdrawn|정정|철회|오류)/i.test(bodyOf(candidate))) return "correction"; if (sameSource) return "substantive-update"; return titleScore >= .9 ? "duplicate" : "unresolved"; }
export function buildUpdateReport() { const prior = existing(); const rows = drafts().map((candidate) => { const matches = prior.map((p) => ({ p, score: Math.max(titleSimilarity(candidate.title || candidate.sourceTitle, p.sourceTitle || p.titleKo || p.title), candidate.sourceUrl && p.sourceUrl && candidate.sourceUrl === p.sourceUrl ? 1 : 0) })).sort((a, b) => b.score - a.score); const match = matches[0]?.score >= .72 ? matches[0].p : null; const classification = classifyUpdate(candidate, match); return { candidateId: candidate.id, classification, candidate: { title: candidate.title || candidate.sourceTitle, sourceUrl: candidate.sourceUrl, sourceUrlRaw: candidate.sourceUrlRaw, publishedAt: candidate.publishedAt, sourceHash: candidate.sourceHash || candidate.sourceContentHash || null, contentHash: candidate.contentHash || null }, existing: match ? { id: match.id, title: match.titleKo || match.title, date: match._date, sourceUrl: match.sourceUrl || null, sourceHash: match.sourceHash || null, contentHash: match.contentHash || null } : null, comparison: { titleSimilarity: matches[0]?.score || 0, sameSource: Boolean(match && candidate.sourceUrl && match.sourceUrl && candidate.sourceUrl === match.sourceUrl), candidateNumbers: numbers(candidate), existingNumbers: match ? numbers(match) : [], sourceDateDeltaDays: match?.publishedAt && candidate.publishedAt ? Math.abs(Date.parse(match.publishedAt) - Date.parse(candidate.publishedAt)) / 86400000 : null }, approval: { dryRun: true, command: `npm run updates:approve -- ${candidate.id}` } }; }); const counts = Object.fromEntries(["duplicate", "minor-update", "substantive-update", "correction", "separate-story", "unresolved"].map((x) => [x, rows.filter((r) => r.classification === x).length])); return { generatedAt: new Date().toISOString(), counts, rows, note: "분류는 검수 후보이며 기존 기사를 자동 덮어쓰지 않습니다." }; }
function save(report) { atomicWrite(OUT, JSON.stringify(report, null, 2) + "\n"); atomicWrite(path.join(ROOT, "reports", "update-candidates.md"), `# Update 후보\n\n- 실행 시각: ${report.generatedAt}\n- 분포: ${JSON.stringify(report.counts)}\n\n${report.rows.map((r) => `- ${r.classification} · ${r.candidateId} · ${r.candidate.title}`).join("\n")}\n`); }
function reviewer(id) { const people = readJson(path.join(ROOT, "data", "editorial", "people.json"), []); return (Array.isArray(people) ? people : people.people || []).find((p) => p.id === id || p.slug === id); }
function cli(command, id, flags) { const report = readJson(OUT, null) || buildUpdateReport(); const row = report.rows.find((r) => r.candidateId === id); if (!row) throw new Error(`update 후보를 찾을 수 없습니다: ${id}`); const plan = { ...row, command, apply: Boolean(flags.apply), reviewerId: flags["reviewer-id"] || null }; console.log(JSON.stringify(plan, null, 2)); if (command === "approve" && flags.apply) { if (!reviewer(flags["reviewer-id"])) throw new Error("등록된 reviewerId가 필요합니다"); if (row.classification === "minor-update") throw new Error("minor-update는 dateModified를 변경하지 않으므로 자동 적용하지 않습니다"); fs.mkdirSync(path.dirname(DECISIONS), { recursive: true }); fs.appendFileSync(DECISIONS, JSON.stringify({ ...plan, decidedAt: new Date().toISOString(), previousStatus: "candidate", newStatus: row.classification === "correction" ? "correction-required" : "approved" }) + "\n"); } }
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const command = process.argv[2] || "stats"; const id = process.argv[3]; const flags = Object.fromEntries(process.argv.slice(3).filter((x) => x.startsWith("--")).map((x) => { const [k, ...v] = x.slice(2).split("="); return [k, v.length ? v.join("=") : true]; }));
  try { if (command === "stats" || command === "next") { const report = buildUpdateReport(); save(report); console.log(JSON.stringify(command === "next" ? report.rows.slice(0, 20) : report.counts, null, 2)); } else if (command === "compare" || command === "approve" || command === "reject") cli(command, id, flags); else throw new Error("stats | next | compare ID | approve ID [--apply --reviewer-id=ID] | reject ID"); } catch (e) { console.error(e.message); process.exit(1); }
}
